### PR TITLE
[ARCHETYPE-612] Fixes to required property sort approach

### PR DESCRIPTION
**Pull request by dhutchison**
Fix for [ARCHETYPE-612](https://issues.apache.org/jira/browse/ARCHETYPE-612).

This implementation will now respect the required property order defined by the archetype author,
unless they have interdependencies which are not ordered correctly. If properties are detected to be in the wrong order, it will use a (slightly simplistic) graph traversal approach to find a working sort order. 

This removes the previous behaviour where it would try to sort based on dependencies, while aiming for alphabetic property order with fixed core property order.

### CODE REVIEW

**Comment by jaredculp** [comment]
Is there a way to work around this issue in the meantime?

**Comment by dhutchison** [comment]
The only way I could find was to get people to specify properties on the command line instead of using the interactive prompts.

**Comment by jaredculp** [comment]
Yeah we basically decided to write a shell script as a wrapper which does all the parsing and then passes the values to the archetype in batch mode.

**Comment by dhutchison** [comment]
Closing this as #64 says it supersedes this.

**Comment by jira-importer** [comment]
Resolve #865

**Comment by jira-importer** [comment]
Resolve #865

**Pull request closed without merging**
