### PR TITLE
[ARCHETYPE-679] Add additional modules for groovy

### PR DESCRIPTION
**Pull request by slawekjaranowski**
- groovy-templates
- groovy-xml
- groovy-yaml

https://issues.apache.org/jira/browse/ARCHETYPE-679

### CODE REVIEW

**Review by cstamas — APPROVED** [review]

**Comment by jGauravGupta** [comment]
Hi, Thank you for addressing this issue in Archetype! Is there any update on when we can expect the release of Archetype 3.3.1?

**Comment by slawekjaranowski** [comment]
> Hi, Thank you for addressing this issue in Archetype! Is there any update on when we can expect the release of Archetype 3.3.1?

I will do next release in a few days.

**Comment by jira-importer** [comment]
Resolve #885

**Comment by jira-importer** [comment]
Resolve #885

**Comment by jira-importer** [comment]
Resolve #885

**Comment by jira-importer** [comment]
Resolve #885

**Pull request merged**
