### PR TITLE
[ARCHETYPE-626] mvn install deploy does not work with 3.2.1

### PR DESCRIPTION
**Pull request by JanMosigItemis**
Hi there,

thought I'd provide a fix for this problem. Although I do not know why writing to output directory (i. e. target/classes) confuses Velocity's template merge algorithm, I do think that writing the archetype-settings.xml to test output directory (i. e. target/test-classes) is a better idea anyway, because it is meant for test stuff. By doing so, the problem seems to be gone and it does not seem to do any harm.

Regards

### CODE REVIEW

**Comment by hboutemy** [comment]
it looks like #188 supercedes this

**Comment by JanMosigItemis** [comment]
Thx for the hint @hboutemy. Does #188 still miss tests?

**Comment by hboutemy** [comment]
test was useful when we were fighting a regression, without really knowing why
with #188, it's not a regression but a change with a purpose in mind: I just did not expect this would solve also ARCHETYPE-626 :)

**Comment by jira-importer** [comment]
Resolve #862

**Comment by jira-importer** [comment]
Resolve #862

**Pull request closed without merging**
