### PR TITLE
[ARCHTYPE-308] optionally ask for properties with default values in

### PR DESCRIPTION
**Pull request by kwin**
interactive mode

### CODE REVIEW

**Review by newblaque — APPROVED** [review]

**Comment by gunnarmorling** [comment]
Hey @hboutemy, pinging you as I saw you recently committed to this repo. I am interested in seeing a solution to this issue here, so I'm wondering what is missing in order to resolve it? I'd be willing to help if there's need for it. In terms of a solution, I think what's proposed here is good, only that'd I'd preferably make the new behavior the default (i.e. prompt for default options unless it's disabled explicitly). Alternatively, whether to prompt or not prompt could be a part of the archetype definition. WDYT?

**Comment by slachiewicz** [comment]
could you rebase PR - we have conflict here: 137461e8dd71a26f53d25aa9c58e29e04127d6a7

**Comment by kwin** [comment]
@slachiewicz I now rebased my PR.

**Comment by jira-importer** [comment]
Resolve #684

**Comment by jira-importer** [comment]
Resolve #684

**Pull request merged**
