### PR TITLE
[ARCHETYPE-618]

### PR DESCRIPTION
**Pull request by mbenson**

### CODE REVIEW

**Comment by mbenson** [comment]
@elharo Sorry to drag you into this, but the last PR was lacking and this one improves upon it. I'd hate for a solution with known problems to make it into a release.

**Review by elharo — APPROVED** [review]

**Comment by mbenson** [comment]
One approval, now what? :)

**Comment by michael-o** [comment]
> 
> 
> One approval, now what? :)

Now you need someone with balls to merge it.

**Review by rmannibucau — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #853

**Comment by jira-importer** [comment]
Resolve #853

**Comment by jira-importer** [comment]
Resolve #853

**Comment by jira-importer** [comment]
Resolve #853

**Pull request merged**
