### PR TITLE
[ARCHETYPE-643] update Java version to 1.8

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Comment by slachiewicz** [comment]
Probably integration tests also needs review to set src/target Java to 8. Check if here is no redundant settings for TLS

**Review by slachiewicz — APPROVED** [review]

**Comment by slachiewicz** [comment]
builds ok with java 20 so no visible issues with src/target java. lgtm

**Comment by slachiewicz** [comment]
worth to bump project version

**Comment by elharo** [comment]
Which would be the next version? i.e. bump major, minor, or patch?

**Comment by elharo** [comment]
> Probably integration tests also needs review to set src/target Java to 8. Check if here is no redundant settings for TLS

You mean I should delete lines like:

```
              <!-- e.g. ensure that Java7 picks up TLSv1.2 when connecting with Central -->
              <https.protocols>${https.protocols}</https.protocols>
```

**Comment by elharo** [comment]
I remove the TLS settings. Integration tests seem fine after quick review.

**Review by slachiewicz — APPROVED** [review]

**Comment by elharo** [comment]
I hope this is just flaky, rerunning:

```
[INFO] Building: create-3/pom.xml
[INFO] run post-build script verify.groovy
[INFO]   The post-build script did not succeed. assert template.exists()
       |        |
       |        false
       /Users/runner/work/maven-archetype/maven-archetype/maven-archetype-plugin/target/it/projects/create-3/target/generated-sources/archetype/src/main/resources/archetype-resources/pom.xml
```

**Comment by jira-importer** [comment]
Resolve #904

**Pull request merged**
