### PR TITLE
[ARCHETYPE-569] Update to latest version of plexus utils

### PR DESCRIPTION
**Pull request by mbooth101**
Signed-off-by: Mat Booth <mat.booth@redhat.com>

### CODE REVIEW

**Comment by Tibor17** [comment]
@mbooth101 
LGTM
Did you run the build successfully on JDK 1.7 and higher? No issues found?

**Comment by Tibor17** [comment]
@mbooth101 
There's a [build failure](https://builds.apache.org/job/maven-box/job/maven-archetype/job/ARCHETYPE-569/1/console). Would you investigate it? Thx.

**Comment by mbooth101** [comment]
> @mbooth101
> There's a [build failure](https://builds.apache.org/job/maven-box/job/maven-archetype/job/ARCHETYPE-569/1/console). Would you investigate it? Thx.

The failure happens after the maven build completes successfully. I'm sorry I cannot debug this because I cannot view your Jenkins job configurations.

**Comment by Tibor17** [comment]
@mbooth101 
Open full logs like this https://builds.apache.org/job/maven-box/job/maven-archetype/job/ARCHETYPE-569/1/consoleFull
Lookup the message `[ERROR] The following builds failed:` It is a specific error on Windows. We have to reproduce it on Windows and find the root cause.

**Comment by mbooth101** [comment]
So this has interleaved logs from all the build platforms? Ouch...

Unfortunately I have no access to a Windows machine :-( Any chance you can the pull the logs that the failures mention? E.g.:

```
[INFO] run post-build script verify.groovy
[INFO]           included-system-properties\pom.xml ............... FAILED (8.0 s)
[INFO]   The build exited with code 1. See F:\short\jenkins-maven-box-maven-archetype-ARCHETYPE-569-1@3\j7m3.6.xb\maven-archetype-plugin\target\it\projects\included-system-properties\build.log for details.
```

**Comment by Tibor17** [comment]
The [BlueOcean](https://builds.apache.org/blue/organizations/jenkins/maven-box%2Fmaven-archetype/detail/ARCHETYPE-569/1/pipeline) will help you. The logs do not interleave.
The logs only tell you that we have a problem but it does not tell you where. You can enable streaming logs in the config for `maven-invoker-plugin`. If this still does not help, we have to run it on local Windows.

**Comment by mbooth101** [comment]
> The [BlueOcean](https://builds.apache.org/blue/organizations/jenkins/maven-box%2Fmaven-archetype/detail/ARCHETYPE-569/1/pipeline) will help you.

This link is 404

> The logs do not interleave.

Well, I'm pretty sure the platform labels on the left side indicate from which platform that segment of log is from -- It would be easier to read the log from just the failing platform IMO, but oh well.

> The logs only tell you that we have a problem but it does not tell you where. You can enable streaming logs in the config for `maven-invoker-plugin`.

Sure I guess I can enable that in my PR -- Will the build retrigger automatically?

**Comment by Tibor17** [comment]
BlueOcean has search on the top of the page. Use it and type `maven-archetype`. This works for me.

**Comment by Tibor17** [comment]
> Sure I guess I can enable that in my PR -- Will the build retrigger automatically?

No. We disabled this feature. Therefore I had to make a branch in our ASF repo because GitHub is only a mirror repo.

**Comment by mbooth101** [comment]
> > Sure I guess I can enable that in my PR -- Will the build retrigger automatically?
> 
> No. We disabled this feature. Therefore I had to make a branch in our ASF repo because GitHub is only a mirror repo.

I see, do you have a different, more preferred way of receiving patches with automatic CI?

**Comment by Tibor17** [comment]
there's no other way yet.

@eolivelli 
Hi Enrico. Can you add TravisCi build in this project too? Thx.

**Comment by mbooth101** [comment]
Can you please retrigger the build including commit b87bafd ?

Hopefully there will be enough info to see what is wrong.

**Comment by eolivelli** [comment]
@Tibor17 I will be happy to do it once I am back from vacation.
We just only have to add the Travis file and create an INFRA ticket to request the activation

**Comment by Tibor17** [comment]
@mbooth101 
You can push a new pr with the TraviceCi script, see https://github.com/apache/maven-surefire/blob/master/.travis.yml  but the script should be `mvn clean verify -P run-its`. I will push it directly to ASF and I will contact INFRA. Then we will rebase this pr and we should hopefully see the build result here.

**Comment by Tibor17** [comment]
@mbooth101 
Let's see. Now the second build is running  https://builds.apache.org/job/maven-box/job/maven-archetype/job/ARCHETYPE-569/2/

**Comment by mbooth101** [comment]
> @mbooth101
> Let's see. Now the second build is running https://builds.apache.org/job/maven-box/job/maven-archetype/job/ARCHETYPE-569/2/

Hmm, the set of platforms that failed is different this time, compare: https://builds.apache.org/job/maven-box/job/maven-archetype/job/ARCHETYPE-569/

So there is intermittent problem on Windows. :-/

**Comment by Tibor17** [comment]
This is the [log from Mvn3.6/Java11](https://gist.github.com/Tibor17/2953fe918b023e01a70bb1ec44021012)
it is unable to download other plugin from MC.

I have manually triggered the build for the latest `master`.
https://builds.apache.org/job/maven-box/job/maven-archetype/job/master/31/
Let's compare both branches.

**Comment by mbooth101** [comment]
> This is the [log from Mvn3.6/Java11](https://gist.github.com/Tibor17/2953fe918b023e01a70bb1ec44021012)
> it is unable to download other plugin from MC.
> 
> I have manually triggered the build for the latest `master`.
> https://builds.apache.org/job/maven-box/job/maven-archetype/job/master/31/
> Let's compare both branches.

So master is also failing intermittently on Windows?

**Comment by Tibor17** [comment]
> So master is also failing intermittently on Windows?

It looks so.
We have similar problem in `maven-site-plugin` too.
Maybe you could see my email in [dev](https://lists.apache.org/thread.html/2afa3853b83d1c25ddfef2d8016b59d70fae8759b941bc4a56423767@%3Cdev.maven.apache.org%3E)
I am waiting for replied answers on our mailing list. This is a bad situation because now I cannot trust to anything.

**Comment by Tibor17** [comment]
@mbooth101 
Can you rebase this PR to master?
I want to start a new release today.
The build is hopefully stable, so we can continue with your commit.

**Comment by jira-importer** [comment]
Resolve #852

**Comment by jira-importer** [comment]
Resolve #852

**Pull request merged**
