### PR TITLE
Fix import order in ArchetypeConfiuration

### PR DESCRIPTION
**Pull request by mryan43**

### CODE REVIEW

**Comment by michael-o** [comment]
Where is the need for this fix? `O` comes after `J`.

**Comment by mryan43** [comment]
I just want to make it coherent with other source files in this project so that contributors can configure their IDE to order the imports properly and avoid unrelated changes due to automatic reordering.

I don't really care if we change this file or all the other source files in the project... I just want it to be coherent.

**Comment by michael-o** [comment]
Agreed.

**Comment by michael-o** [comment]
@mryan43 Please close the PR.

**Pull request closed without merging**
