### PR TITLE
[MARCHETYPE-596] update xmlunit

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Comment by elharo** [comment]
Curious how this gives a red build AND "Test Result (no failures)"

**Comment by rfscholte** [comment]
It was not a test that failed. 

[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-bytecode-version) @ archetype-common ---
[INFO] Restricted to JDK 1.7 yet javax.xml.bind:jaxb-api:jar:2.3.0:test contains META-INF/versions/9/javax/xml/bind/ModuleUtil.class targeted to JDK 1.9
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.EnforceBytecodeVersion failed with message:
Found Banned Dependency: javax.xml.bind:jaxb-api:jar:2.3.0
Use 'mvn dependency:tree' to locate the source of the banned dependencies.

On 16-4-2020 20:24:47, Elliotte Rusty Harold <notifications@github.com> wrote:
Curious how this gives a red build AND "Test Result (no failures)"

**Comment by elharo** [comment]
Hmm, shouldn't that be an ERROR, not a WARNING then?
In either case, is our test here to strict? The problematic byte code is hidden in inside a multi-release jar so it should be OK for any VM that sees it.

**Comment by rfscholte** [comment]
my guess: the rule is set to failOnWarning.
AFAIK most recent version of this rule understands multirelease jar.
On 16-4-2020 20:44:45, Elliotte Rusty Harold <notifications@github.com> wrote:
Hmm, shouldn't that be an ERROR, not a WARNING then?
In either case, is our test here to strict? The problematic byte code is hidden in inside a multi-release jar so it should be OK for any VM that sees it.

**Comment by elharo** [comment]
Updating enforcer rules worked.

**Pull request merged**
