### PR TITLE
[ARCHETYPE-406] Resolve velocity expressions in the order they appear

### PR DESCRIPTION
**Pull request by masterfool**

### CODE REVIEW

**Comment by rfscholte** [comment]
Reading https://issues.apache.org/jira/browse/ARCHETYPE-406 this is not really about ordered properties (as provided in this PR), but being able to access requested property values.

**Comment by jira-importer** [comment]
Resolve #393

**Comment by jira-importer** [comment]
Resolve #393

**Comment by jira-importer** [comment]
Resolve #393

**Pull request closed without merging**
