### PR TITLE
[ARCHETYPE-565] - Unable to resolve groovy.json classes when planting

### PR DESCRIPTION
**Pull request by joshdreagan**
Updated groovy dependency to groovy-all since packages where moved in 2.x

### CODE REVIEW

**Comment by eolivelli** [comment]
Thanks for your fix.

Can you please enhance and existing test case or add a new one?

**Comment by joshdreagan** [comment]
I'd be happy to, but I'm not quite sure what to add/enhance. Since this is just an update to a dependency, I would assume that making sure the existing tests pass would be sufficient. Could you maybe give me a bit more information on what you'd like to see?

**Comment by eolivelli** [comment]
Here we added a script like yours
https://github.com/apache/maven-archetype/commit/11cb603da9d3da813c0a34a9e2532cc2c85f940b#diff-a6aa95e2d0a1da7b4460e2506c2e67daR56

You could follow that example and add your case about Json stuff

**Comment by joshdreagan** [comment]
Ok. Test added.

**Review by eolivelli — APPROVED** [review]
Looks great!

I can't merge it now. Because I am on vacation and I don't have my laptop.
Pls ping me if you don't see it merged within a week

I will also have to trigger CI on Apache Jenkins (this is not automatic for Pull requests for security reasons)

**Comment by eolivelli** [comment]
CI is running
https://ci-builds.apache.org/job/Maven/job/maven-box/job/maven-archetype/job/ARCHETYPE-565/

**Comment by joshdreagan** [comment]
Any update on this? Looks like the CI build failed, but as far as I can tell it was for unrelated reasons.

**Comment by ricardozanini** [comment]
Sorry to jump in... but I'm willing to use `groovy.xml.XmlUtil` and `groovy.util.XmlParser`, but I can't since the `maven-archetype-plugin` do not import the Groovy XML libraries. This PR, though, will fix my issues as well. Can we merge? :)

Or do we have a workaround? I tried adding the libraries to my archetype `pluginManagement` section but no luck.

**Comment by ricardozanini** [comment]
@slachiewicz this one has been merged? 🤔

**Comment by slachiewicz** [comment]
yes https://issues.apache.org/jira/browse/ARCHETYPE-565

**Comment by jira-importer** [comment]
Resolve #572

**Pull request closed without merging**
