### PR TITLE
[ARCHETYPE-642] update plexus-utils to 3.5.1

### PR DESCRIPTION
**Pull request by elharo**
First of several steps needed to bring this up to parent pom 39

### CODE REVIEW

**Comment by elharo** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.2-SNAPSHOT:create-from-project (default-cli) on project archetype531-parent: Failed to copy full contents from /home/jenkins/jenkins-home/workspace/maven-box_maven-archetype_PR-134@2/linux-jdk8-m3.6.x_build/maven-archetype-plugin/target/it/projects/ARCHETYPE-531_ear-modules/build.log to /home/jenkins/jenkins-home/workspace/maven-box_maven-archetype_PR-134@2/linux-jdk8-m3.6.x_build/maven-archetype-plugin/target/it/projects/ARCHETYPE-531_ear-modules/target/generated-sources/archetype/src/main/resources/archetype-resources/build.log -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.2-SNAPSHOT:create-from-project (default-cli) on project archetype531-parent: Failed to copy full contents from /home/jenkins/jenkins-home/workspace/maven-box_maven-archetype_PR-134@2/linux-jdk8-m3.6.x_build/maven-archetype-plugin/target/it/projects/ARCHETYPE-531_ear-modules/build.log to /home/jenkins/jenkins-home/workspace/maven-box_maven-archetype_PR-134@2/linux-jdk8-m3.6.x_build/maven-archetype-plugin/target/it/projects/ARCHETYPE-531_ear-modules/target/generated-sources/archetype/src/main/resources/archetype-resources/build.log

**Comment by elharo** [comment]
OK, looks like the problem is simply that our CI is flaky.

**Review by michael-o — APPROVED** [review]

**Comment by slachiewicz** [comment]
https://issues.apache.org/jira/browse/ARCHETYPE-642 version updated

**Comment by jira-importer** [comment]
Resolve #873

**Comment by jira-importer** [comment]
Resolve #873

**Pull request merged**
